CREATE DATABASE AULA3_JOIN
GO
USE AULA3_JOIN


CREATE TABLE CANDIDATO(

	ID_CANDIDATO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	PROFISSAO VARCHAR(50)
)

CREATE TABLE VAGA(
	
	ID_VAGA INT IDENTITY (1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(100),	
)
CREATE TABLE CANDIDATURA(
	
	ID_CANDIDATURA INT IDENTITY(1,1) PRIMARY KEY,
	ID_VAGA INT NOT NULL REFERENCES VAGA(ID_VAGA),
	ID_CANDIDATO INT NOT NULL REFERENCES CANDIDATO(ID_CANDIDATO),
	DATA_CANDIDATURA DATE
)


INSERT INTO CANDIDATO(NOME, PROFISSAO) VALUES ('Lucas Koerich', 'Dev Fullstack'), ('Vitor Lassen', 'Dev .NET'), ('João Gomes', 'Dev Angular'), ('Ana Julia', 'Dev Fullstack')

INSERT INTO VAGA(DESCRICAO) VALUES ('Desenvolvedor Fullstack'), ('Faxineira'), ('Desenvolvedor Angular')

INSERT INTO CANDIDATURA(ID_VAGA, ID_CANDIDATO, DATA_CANDIDATURA) VALUES (1, 1, '2023-03-16'), (1, 4, '2023-03-16'), (3, 3, '2023-03-16')  


SELECT * FROM VAGA
SELECT * FROM CANDIDATO
SELECT * FROM CANDIDATURA




SELECT * FROM CANDIDATO
INNER JOIN CANDIDATURA ON CANDIDATO.ID_CANDIDATO = CANDIDATURA.ID_CANDIDATO	
INNER JOIN VAGA ON VAGA.ID_VAGA = CANDIDATURA.ID_CANDIDATURA

SELECT * FROM CANDIDATO 
LEFT JOIN CANDIDATURA ON CANDIDATO.ID_CANDIDATO = CANDIDATURA.ID_CANDIDATO
LEFT JOIN VAGA ON VAGA.ID_VAGA = CANDIDATURA.ID_VAGA
WHERE ID_CANDIDATURA IS NOT NULL
