CREATE DATABASE AULA4
GO
USE AULA4


CREATE TABLE CLIENTE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50)
)

CREATE TABLE TELEFONE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT REFERENCES CLIENTE(ID),
	TELEFONE VARCHAR(12)
)

INSERT INTO CLIENTE(NOME) VALUES ('Lucas')

DECLARE @ID_CLIENTE INT 
SET @ID_CLIENTE = SCOPE_IDENTITY()


INSERT INTO TELEFONE(ID_CLIENTE, TELEFONE) VALUES (@ID_CLIENTE,'48985003513')

SELECT * FROM CLIENTE 
JOIN TELEFONE T ON T.ID_CLIENTE = ID_CLIENTE


SELECT * FROM TELEFONE

