USE AULA3_SLIDE

SELECT ID AS 'NUMERO CLIENTE', NOME, TELEFONE, ID_CLIENTE
FROM CLIENTES C
JOIN TELEFONES T ON T.ID_CLIENTE = C.ID


DECLARE @NUMERO INT

SET @NUMERO = 8

SELECT * FROM CLIENTES WHERE NOME = 'Graziela'


SELECT @NUMERO = ID FROM CLIENTES WHERE NOME = 'Graziela'
SELECT @NUMERO
PRINT @NUMERO

DROP DATABASE AULA4_EXERCICIO