CREATE DATABASE AULA2
GO
USE AULA2

-- RELACIONAMENTO 1:N 

CREATE TABLE PAIS(	

	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(50),
	DATANASCIMENTO DATE, 
	PROFISSAO VARCHAR(50),
);

CREATE TABLE FILHOS(
	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(50),
	DATANASCIMENTO DATE, 
	ID_PAI INT REFERENCES PAIS(ID),

);

INSERT INTO PAIS (NOME, SOBRENOME, PROFISSAO, DATANASCIMENTO) 
       VALUES ('João', 'Afonso', 'Marceneiro', '1980-11-12')

INSERT INTO PAIS (NOME, SOBRENOME, PROFISSAO, DATANASCIMENTO) 
       VALUES ('Julia', 'Giandio', 'Herdeira', '1995-10-17')

SELECT * FROM PAIS


INSERT INTO FILHOS (NOME, SOBRENOME, DATANASCIMENTO, ID_PAI)
	   VALUES ('Guilhermo', 'Afonso', '2001-05-14', 1)

INSERT INTO FILHOS (NOME, SOBRENOME, DATANASCIMENTO, ID_PAI)
	   VALUES ('Ana', 'Afonso', '2005-04-25', 1)

INSERT INTO FILHOS (NOME, SOBRENOME, DATANASCIMENTO, ID_PAI)
	   VALUES ('Julio', 'Giandio', '2004-01-06', (
	   SELECT ID FROM PAIS WHERE NOME = 'Julia'))

SELECT * FROM FILHOS



-- RELACIONAMENTO 1:1

CREATE TABLE ESPOSA(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(50),
);

CREATE TABLE ESPOSO(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(50),
	ID_ESPOSA INT REFERENCES ESPOSA(ID) UNIQUE
);

INSERT INTO ESPOSA (NOME, SOBRENOME) VALUES ('Joana', 'Zicker')

INSERT INTO ESPOSO (NOME, SOBRENOME, ID_ESPOSA)
	   VALUES ('Fernando', 'Zicker', (SELECT ID FROM ESPOSA WHERE NOME = 'Joana'))

--INSERT INTO ESPOSO (NOME, SOBRENOME, ID_ESPOSA)
--	   VALUES ('Zé', 'Bananeira', (SELECT ID FROM ESPOSA WHERE NOME = 'Joana'))
	   
	
SELECT * FROM ESPOSO
SELECT * FROM ESPOSA



-- RELACIONAMENTO N:N

CREATE TABLE MATERIAS (

	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATERIA VARCHAR(20)
);

CREATE TABLE ALUNOS (

	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50)
);

CREATE TABLE MATERIAS_X_ALUNOS(

	ID_ALUNO INT REFERENCES ALUNOS(ID) NOT NULL,
	ID_MATERIA INT REFERENCES MATERIAS(ID) NOT NULL
);

ALTER TABLE MATERIAS_X_ALUNOS ADD PRIMARY KEY (ID_ALUNO, ID_MATERIA)


INSERT INTO MATERIAS(MATERIA) VALUES ('Introdução ao C#'), ('Introdução ao SQL')

INSERT INTO ALUNOS(NOME) VALUES ('Carlos'), ('Fernando'), ('Isadora'), ('Analu')

INSERT INTO MATERIAS_X_ALUNOS(ID_ALUNO, ID_MATERIA) VALUES (1, 1), (1, 2) 
INSERT INTO MATERIAS_X_ALUNOS(ID_ALUNO, ID_MATERIA) VALUES (2, 1)
INSERT INTO MATERIAS_X_ALUNOS(ID_ALUNO, ID_MATERIA) VALUES (3, 2)
INSERT INTO MATERIAS_X_ALUNOS(ID_ALUNO, ID_MATERIA) VALUES (4, 1), (4, 2) 


SELECT * FROM MATERIAS
SELECT * FROM ALUNOS
SELECT * FROM MATERIAS_X_ALUNOS




