// <auto-generated />
using System;
using Aula02.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aula02.Migrations
{
    [DbContext(typeof(MesContext))]
    partial class MesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aula02.Models.MesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MES");
                });

            modelBuilder.Entity("Aula02.Models.SemanaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("IdMes")
                        .HasColumnType("int");

                    b.Property<int?>("MesModel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MesModel");

                    b.ToTable("SEMANA");
                });

            modelBuilder.Entity("Aula02.Models.SemanaModel", b =>
                {
                    b.HasOne("Aula02.Models.MesModel", "Mes")
                        .WithMany()
                        .HasForeignKey("MesModel");

                    b.Navigation("Mes");
                });
#pragma warning restore 612, 618
        }
    }
}
