CREATE DATABASE EXERCICIO2_SEMANA7
GO
USE EXERCICIO2_SEMANA7


-- CRIAÇÃO DA TABELA

CREATE TABLE FUNCIONARIO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	CARGO VARCHAR(50),
	TELEFONE1 VARCHAR(12),
	TELEFONE2 VARCHAR(12)
)


-- 1a FORMA NORMAL e 2a FORMA NORMAL

ALTER TABLE FUNCIONARIO DROP COLUMN TELEFONE1, TELEFONE2

CREATE TABLE TELEFONE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_FUNCIONARIO INT REFERENCES FUNCIONARIO(ID),
	TELEFONE VARCHAR(12)
)

-- 3a FORMA NORMAL

ALTER TABLE FUNCIONARIO DROP COLUMN CARGO

CREATE TABLE CARGO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME_CARGO VARCHAR(50)
)

ALTER TABLE FUNCIONARIO ADD CARGO INT REFERENCES CARGO(ID)


INSERT INTO FUNCIONARIO(NOME) VALUES ('Luana'), ('Carlos'), ('Josh')
INSERT INTO CARGO(NOME_CARGO) VALUES ('Atendente'), ('Gerente')

DECLARE @ID_FUNCIONARIO INT

SELECT @ID_FUNCIONARIO = ID FROM FUNCIONARIO WHERE ID = 1
INSERT INTO TELEFONE(ID_FUNCIONARIO, TELEFONE) VALUES (@ID_FUNCIONARIO, '4898500'), (@ID_FUNCIONARIO, '78445')
UPDATE FUNCIONARIO SET CARGO = 1 WHERE ID = @ID_FUNCIONARIO

SELECT @ID_FUNCIONARIO = ID FROM FUNCIONARIO WHERE ID = 2
INSERT INTO TELEFONE(ID_FUNCIONARIO, TELEFONE) VALUES (@ID_FUNCIONARIO, '4898'), (@ID_FUNCIONARIO, '245')
UPDATE FUNCIONARIO SET CARGO = 1 WHERE ID = @ID_FUNCIONARIO

SELECT @ID_FUNCIONARIO = ID FROM FUNCIONARIO WHERE ID = 3
INSERT INTO TELEFONE(ID_FUNCIONARIO, TELEFONE) VALUES (@ID_FUNCIONARIO, '464500'), (@ID_FUNCIONARIO, '88445')
UPDATE FUNCIONARIO SET CARGO = 2 WHERE ID = @ID_FUNCIONARIO

