CREATE DATABASE AULA4_EXERCICIO
GO
USE AULA4_EXERCICIO

CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	CPF VARCHAR(15) UNIQUE NOT NULL,
	TELEFONE VARCHAR(12),
	ENDERECO VARCHAR(50)
)

CREATE TABLE ITEM(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	VALOR SMALLMONEY NOT NULL
)

CREATE TABLE VENDA(
	DATA_VENDA DATE NOT NULL,
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT REFERENCES CLIENTE(ID)
)

ALTER TABLE CLIENTE DROP COLUMN TELEFONE, ENDERECO

CREATE TABLE ENDERECO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT REFERENCES CLIENTE(ID),
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL
)

CREATE TABLE TELEFONE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT REFERENCES CLIENTE(ID),
	NUMERO VARCHAR(12)
)

CREATE TABLE VENDA_X_ITEM(
	ID_VENDA INT REFERENCES VENDA(ID),
	ID_ITEM INT REFERENCES ITEM(ID)
)

INSERT INTO CLIENTE(NOME, CPF) VALUES ('Lucas', '123456'), ('Vanessa', '789456'), ('Joseane', '123789')


DECLARE @ID_CLIENTE INT

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '123456'
INSERT INTO TELEFONE(ID_CLIENTE, NUMERO) VALUES (@ID_CLIENTE, '48985003513')


SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '789456'
INSERT INTO TELEFONE(ID_CLIENTE, NUMERO) VALUES (@ID_CLIENTE, '48984740147')

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '123789'
INSERT INTO TELEFONE(ID_CLIENTE, NUMERO) VALUES (@ID_CLIENTE, '47994540158')



SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '123456'
INSERT INTO ENDERECO(ID_CLIENTE, RUA, BAIRRO, NUMERO) VALUES (@ID_CLIENTE, 'Rua Joaquim Pereira', 'Coqueiros', 125) 

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '789456'
INSERT INTO ENDERECO(ID_CLIENTE, RUA, BAIRRO, NUMERO) VALUES (@ID_CLIENTE, 'Rua Antonio Fagundes', 'Estreito', 344) 

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '123789'
INSERT INTO ENDERECO(ID_CLIENTE, RUA, BAIRRO, NUMERO) VALUES (@ID_CLIENTE, 'Rua Limões', 'Barreiros', 3541) 



INSERT INTO ITEM (NOME, DESCRICAO, VALOR) VALUES ('Coca-Cola', 'Refrigerante', 8.99), ('Pizza Sadia Calabresa', 'Pizza Sadia sabor Calabresa', 14.99), ('Melância', 'Fruta', 1.99)



SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '123456'
INSERT INTO VENDA (DATA_VENDA, ID_CLIENTE) VALUES ('2023-03-17',@ID_CLIENTE)

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '789456'
INSERT INTO VENDA (DATA_VENDA, ID_CLIENTE) VALUES ('2023-03-17',@ID_CLIENTE)

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '123789'
INSERT INTO VENDA (DATA_VENDA, ID_CLIENTE) VALUES ('2023-03-17',@ID_CLIENTE)



DECLARE @ID_VENDA INT, @ID_ITEM INT


SELECT @ID_VENDA = VENDA.ID FROM VENDA JOIN CLIENTE C ON C.ID = VENDA.ID_CLIENTE WHERE C.CPF = '123789'
SELECT @ID_ITEM = ID FROM ITEM WHERE NOME = 'Coca-Cola'
INSERT INTO VENDA_X_ITEM(ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)
SELECT @ID_ITEM = ID FROM ITEM WHERE NOME = 'Melância'
INSERT INTO VENDA_X_ITEM(ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)

SELECT @ID_VENDA = VENDA.ID FROM VENDA JOIN CLIENTE C ON C.ID = VENDA.ID_CLIENTE WHERE C.CPF = '789456'
SELECT @ID_ITEM = ID FROM ITEM WHERE NOME = 'Coca-Cola'
INSERT INTO VENDA_X_ITEM(ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)
SELECT @ID_ITEM = ID FROM ITEM WHERE NOME = 'Pizza Sadia Calabresa'
INSERT INTO VENDA_X_ITEM(ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)

SELECT @ID_VENDA = VENDA.ID FROM VENDA JOIN CLIENTE C ON C.ID = VENDA.ID_CLIENTE WHERE C.CPF = '123456'
SELECT @ID_ITEM = ID FROM ITEM WHERE NOME = 'Melância'
INSERT INTO VENDA_X_ITEM(ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)


SELECT * FROM VENDA
JOIN CLIENTE ON CLIENTE.NOME = CLIENTE.NOME

SELECT * FROM VENDA
JOIN ITEM ON ITEM.NOME = ITEM.NOME



